networks:
  proxy:
    name: backbone_proxy
    external: true
  database:
    name: backbone_database
    external: true

services:
  partdb:
    image: jbtronics/part-db1:v2.3.0
    container_name: partdb
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.partdb.tls=true
      - traefik.http.routers.partdb.tls.certresolver=${CERTRESOLVER:-}
      - traefik.http.routers.partdb.rule=Host("${APPLICATION_FQDN}")
      - traefik.http.routers.partdb.service=partdb-service
      - traefik.http.services.partdb-service.loadbalancer.server.port=80
    environment:
      TZ: Europe/Berlin
      DATABASE_URL: mysql://${DB_USER:-partdb}:${DB_PASSWD:?error}@mariadb:3306/partdb
      DB_AUTOMIGRATE: true
      APP_ENV: docker
      DEFAULT_LANG: en
      DEFAULT_TIMEZONE: Europe/Berlin
      BASE_CURENCY: EUR
      INSTANCE_NAME: "${APPLICATION_NAME}"
      USE_GRAVATAR: true
      TRUSTED_PROXIES: 172.16.0.0/12
    volumes:
      - ./partdb/uploads:/var/www/html/uploads
      - ./partdb/public_media:/var/www/html/public/media
    networks:
      - database
      - proxy
